@startuml C4_context_credit_standart
!include <c4/C4_Context.puml>

LAYOUT_WITH_LEGEND()
title Контекст: Заявка на кредит онлайн

Person(Клиент, "Клиент")

System(Сайт, "Сайт")
System(Интернет_банк, "Интернет-банк")

System_Boundary(bank, "Банк «Стандарт»") {
  System(Шлюз_кредитов, "Шлюз кредитных заявок", "Новый компонент")
  System(Кредитный_конвейер, "Кредитный конвейер", "Camunda")
  System(Скоринг, "Система кредитного скоринга", "Python/Flask")
  System(АБС, "АБС", "Delphi/Oracle")
}

System(БКИ, "Бюро кредитных историй", "Внешний API")
System(СМС_шлюз, "СМС-шлюз", "Телеком-оператор")

Клиент --> Сайт
Клиент --> Интернет_банк
Сайт --> Шлюз_кредитов
Интернет_банк --> Шлюз_кредитов
Шлюз_кредитов --> Кредитный_конвейер
Кредитный_конвейер --> Скоринг
Скоринг --> БКИ
Шлюз_кредитов --> СМС_шлюз
Кредитный_конвейер --> АБС : Асинхронно
@enduml